package vue;
import Modele.*;
import saveur.menu;
import Controle.Factory;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class Clients extends javax.swing.JFrame {
   private final DefaultTableModel model;

    public Clients() {
        this.model = new DefaultTableModel();
        initComponents();
        afficherClients();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LBLId = new javax.swing.JLabel();
        LBLNom = new javax.swing.JLabel();
        LBLPrenom = new javax.swing.JLabel();
        LBLAdresse = new javax.swing.JLabel();
        LBLTelephone = new javax.swing.JLabel();
        LBLEmail = new javax.swing.JLabel();
        TXTId = new javax.swing.JTextField();
        TXTNom = new javax.swing.JTextField();
        TXTPrenom = new javax.swing.JTextField();
        TXTAdresse = new javax.swing.JTextField();
        TXTTelephone = new javax.swing.JTextField();
        TXTEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabClient = new javax.swing.JTable();
        BTNAjouter = new javax.swing.JButton();
        BTNModifier = new javax.swing.JButton();
        BTNSupprimer = new javax.swing.JButton();
        TXTNationalite = new javax.swing.JTextField();
        LBLNatiionalite = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel1.setText("     CLIENT");

        LBLId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBLId.setText("ID");

        LBLNom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBLNom.setText("NOM");

        LBLPrenom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBLPrenom.setText("PRENOM");

        LBLAdresse.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBLAdresse.setText("ADRESSE");

        LBLTelephone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBLTelephone.setText("TELEPHONE");

        LBLEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBLEmail.setText("EMAIL");

        TXTId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTIdActionPerformed(evt);
            }
        });

        TXTNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNomActionPerformed(evt);
            }
        });

        TXTPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPrenomActionPerformed(evt);
            }
        });

        TXTAdresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTAdresseActionPerformed(evt);
            }
        });

        TXTTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTelephoneActionPerformed(evt);
            }
        });

        TXTEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTEmailActionPerformed(evt);
            }
        });

        TabClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOM", "PRENOM", "NATIONALITE", "ADRESSE", "TELEPHONE", "EMAIL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabClient);

        BTNAjouter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNAjouter.setText("Ajouter");
        BTNAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAjouterActionPerformed(evt);
            }
        });

        BTNModifier.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNModifier.setText("Modifier");
        BTNModifier.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BTNModifierStateChanged(evt);
            }
        });
        BTNModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModifierActionPerformed(evt);
            }
        });

        BTNSupprimer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNSupprimer.setText("Supprimer");

        TXTNationalite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNationaliteActionPerformed(evt);
            }
        });

        LBLNatiionalite.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBLNatiionalite.setText("NATIONALITE");

        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Actualiser");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(BTNSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(114, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addComponent(BTNModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))
                        .addContainerGap(488, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(458, 458, 458)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(LBLTelephone)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TXTTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(LBLAdresse)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TXTAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(LBLNom, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LBLId, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LBLNatiionalite)
                                        .addComponent(LBLPrenom, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(53, 53, 53)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TXTId, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TXTNom, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TXTPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(LBLEmail)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TXTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(TXTNationalite, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLId)
                            .addComponent(TXTId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLNom)
                            .addComponent(TXTNom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLPrenom)
                            .addComponent(TXTPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLNatiionalite)
                            .addComponent(TXTNationalite, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLAdresse)
                            .addComponent(TXTAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLTelephone)
                            .addComponent(TXTTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLEmail)
                            .addComponent(TXTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addContainerGap(86, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTIdActionPerformed

    private void TXTNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNomActionPerformed

    private void TXTPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPrenomActionPerformed

    private void TXTAdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTAdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTAdresseActionPerformed

    private void TXTTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTelephoneActionPerformed

    private void TXTEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEmailActionPerformed

    private void BTNAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAjouterActionPerformed
        // TODO add your handling code here:
        clients cl = new clients();
      cl.setNom(TXTNom.getText());
      cl.setTelephone(TXTPrenom.getText());
      cl.setAddresse(TXTAdresse.getText());
      cl.setEmail(TXTEmail.getText());
      cl.setNationalite(TXTNationalite.getText());
      
      Factory.insertclient(cl);
        
    }//GEN-LAST:event_BTNAjouterActionPerformed

    private void BTNModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModifierActionPerformed
       clients cl = new clients();
      cl.setNom(TXTNom.getText());
      cl.setTelephone(TXTPrenom.getText());
      cl.setAddresse(TXTAdresse.getText());
      cl.setEmail(TXTEmail.getText());
      cl.setNationalite(TXTNationalite.getText());
      
      Factory.updateclient(cl);
    }//GEN-LAST:event_BTNModifierActionPerformed

    private void BTNModifierStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BTNModifierStateChanged
               // TODO add your handling code here:
        
    }//GEN-LAST:event_BTNModifierStateChanged

    private void TXTNationaliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNationaliteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNationaliteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
menu cl= new menu();
       cl.setVisible(rootPaneCheckingEnabled);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         clients cl = new clients();
      cl.setNom(TXTNom.getText());
      cl.setTelephone(TXTPrenom.getText());
      cl.setAddresse(TXTAdresse.getText());
      cl.setEmail(TXTEmail.getText());
      cl.setNationalite(TXTNationalite.getText());
      
      Factory.deleteclient(cl);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void afficherClients(){
        model.addColumn("Nom");
            model.addColumn("Telephone");
            model.addColumn("Addresse");
            model.addColumn("Email");
            model.addColumn("Nationalite");
            ArrayList<clients> cli = new ArrayList();
        cli = Factory.displayclient();
        for(clients cl:cli){
             model.addRow(new Object[]{
                    
                 cl.getNom(),
                 //cl.getPrenom(),
                 cl.getTelephone(),
                 cl.getAddresse(),
                 cl.getEmail(),
                 cl.getNationalite()
                 
                 
                 
             });
             TabClient.setModel(model);
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
            model.setRowCount(0);
        
        ArrayList<clients> cli = new ArrayList();
        cli = Factory.displayclient();
        for(clients cl:cli){
             model.addRow(new Object[]{
                    
                 cl.getNom(),
                 //cl.getPrenom(),
                 cl.getNationalite(),
                 cl.getAddresse(),
                 cl.getTelephone(),
                 cl.getEmail()
             });
             TabClient.setModel(model);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAjouter;
    private javax.swing.JButton BTNModifier;
    private javax.swing.JButton BTNSupprimer;
    private javax.swing.JLabel LBLAdresse;
    private javax.swing.JLabel LBLEmail;
    private javax.swing.JLabel LBLId;
    private javax.swing.JLabel LBLNatiionalite;
    private javax.swing.JLabel LBLNom;
    private javax.swing.JLabel LBLPrenom;
    private javax.swing.JLabel LBLTelephone;
    private javax.swing.JTextField TXTAdresse;
    private javax.swing.JTextField TXTEmail;
    private javax.swing.JTextField TXTId;
    private javax.swing.JTextField TXTNationalite;
    private javax.swing.JTextField TXTNom;
    private javax.swing.JTextField TXTPrenom;
    private javax.swing.JTextField TXTTelephone;
    private javax.swing.JTable TabClient;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void setNom(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setTelephone(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
