package vue;

import Controle.Factory;
import Modele.ProduitsMP;
import Modele.ProduitsPF;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import saveur.menu;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class ProduitFini extends javax.swing.JFrame {

    /**
     * Creates new form ProduitMatierePremiere
     */
     private final DefaultTableModel model;

    public ProduitFini() {
        this.model = new DefaultTableModel();
        initComponents();
        afficherPF();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCpp = new javax.swing.JLabel();
        lblpp = new javax.swing.JLabel();
        lblcateg = new javax.swing.JLabel();
        txtCodePF = new javax.swing.JTextField();
        txtPrixPF = new javax.swing.JTextField();
        txtcategPF = new javax.swing.JTextField();
        lblNomP = new javax.swing.JLabel();
        lblCommentP = new javax.swing.JLabel();
        txtNomPF = new javax.swing.JTextField();
        txtQualitePF = new javax.swing.JTextField();
        btnAjouterPF = new javax.swing.JButton();
        btnSupprimerPF = new javax.swing.JButton();
        jBnModifierPF = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        actualiser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextQuantitePF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduitMP = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(102, 102, 255));

        lblCpp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCpp.setText("Code");

        lblpp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblpp.setText("Prix");

        lblcateg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblcateg.setText("Categorie");

        txtCodePF.setEditable(false);

        lblNomP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomP.setText("Nom");

        lblCommentP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCommentP.setText("Qualite");

        txtNomPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomPFActionPerformed(evt);
            }
        });

        txtQualitePF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQualitePFActionPerformed(evt);
            }
        });

        btnAjouterPF.setText("Ajouter");
        btnAjouterPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterPFActionPerformed(evt);
            }
        });

        btnSupprimerPF.setText("Supprimer");
        btnSupprimerPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerPFActionPerformed(evt);
            }
        });

        jBnModifierPF.setText("Modifier");
        jBnModifierPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnModifierPFActionPerformed(evt);
            }
        });

        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        actualiser.setText("Actualiser");
        actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiserActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Quantite");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblpp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblcateg, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblCommentP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNomP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblCpp, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCodePF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPrixPF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtcategPF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNomPF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtQualitePF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextQuantitePF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAjouterPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBnModifierPF))
                            .addComponent(actualiser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(btnSupprimerPF))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodePF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpp)
                    .addComponent(txtPrixPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcateg)
                    .addComponent(txtcategPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomP)
                    .addComponent(txtNomPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommentP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQualitePF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBnModifierPF)
                        .addComponent(btnSupprimerPF))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextQuantitePF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(btnAjouterPF)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(actualiser))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Produit Fini");

        jTableProduitMP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Code", "Prix", "Categorie", "Nom", "Commentaire"
            }
        ));
        jScrollPane1.setViewportView(jTableProduitMP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomPFActionPerformed

    private void txtQualitePFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQualitePFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualitePFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
menu cl= new menu();
       cl.setVisible(rootPaneCheckingEnabled);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAjouterPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterPFActionPerformed
        // TODO add your handling code here:
        
        ProduitsPF pdft=new ProduitsPF();
        pdft.setNom(txtNomPF.getText());
        pdft.setPrix(Integer.valueOf(txtPrixPF.getText()));
        pdft.setCategorie(txtcategPF.getText());
        pdft.setQualite(txtQualitePF.getText());
        pdft.setQuantite(Integer.valueOf(jTextQuantitePF.getText()));
        
        
        
        Factory.insertproductPF(pdft);
    }//GEN-LAST:event_btnAjouterPFActionPerformed

    private void jBnModifierPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnModifierPFActionPerformed
        // TODO add your handling code here:
        ProduitsPF pdft=new ProduitsPF();
        pdft.setNom(txtNomPF.getText());
        pdft.setPrix(Integer.valueOf(txtPrixPF.getText()));
        pdft.setCategorie(txtcategPF.getText());
        pdft.setQualite(txtQualitePF.getText());
        pdft.setQuantite(Integer.valueOf(jTextQuantitePF.getText()));
        
        Factory.updateproductPF(pdft);
    }//GEN-LAST:event_jBnModifierPFActionPerformed

    private void btnSupprimerPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerPFActionPerformed
        // TODO add your handling code here:
        ProduitsPF pdft=new ProduitsPF();
         pdft.setPrix(Integer.valueOf(txtPrixPF.getText()));
        pdft.setCategorie(txtcategPF.getText());
        pdft.setNom(txtNomPF.getText());
        pdft.setQualite(txtQualitePF.getText());
        pdft.setQuantite(Integer.valueOf(jTextQuantitePF.getText()));
        
        Factory.deleteproductPF(pdft);
    }//GEN-LAST:event_btnSupprimerPFActionPerformed

    public void afficherPF(){
            model.addColumn("Prix");
            model.addColumn("Categorie");
            model.addColumn("Nom");
            model.addColumn("Qualite");
            model.addColumn("Quantite");
            
        
        ArrayList<ProduitsPF> pmf = new ArrayList();
        pmf = Factory.displayproductPF();
        for(ProduitsPF pf:pmf){
             model.addRow(new Object[]{
              pf.getPrix(),
              pf.getCategorie(),
              pf.getNom(),
              pf.getQualite(),
              pf.getQuantite()
             });
             jTableProduitMP.setModel(model);
             }
    }
    private void actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiserActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        ArrayList<ProduitsPF> pmf = new ArrayList();
        pmf = Factory.displayproductPF();
        for(ProduitsPF pf:pmf){
             model.addRow(new Object[]{
              pf.getPrix(),
              pf.getCategorie(),
              pf.getNom(),
              pf.getQualite(),
              pf.getQuantite()
             });
             jTableProduitMP.setModel(model);
             }
    }//GEN-LAST:event_actualiserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProduitFini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProduitFini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProduitFini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProduitFini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProduitFini().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualiser;
    private javax.swing.JButton btnAjouterPF;
    private javax.swing.JButton btnSupprimerPF;
    private javax.swing.JButton jBnModifierPF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProduitMP;
    private javax.swing.JTextField jTextQuantitePF;
    private javax.swing.JLabel lblCommentP;
    private javax.swing.JLabel lblCpp;
    private javax.swing.JLabel lblNomP;
    private javax.swing.JLabel lblcateg;
    private javax.swing.JLabel lblpp;
    private javax.swing.JTextField txtCodePF;
    private javax.swing.JTextField txtNomPF;
    private javax.swing.JTextField txtPrixPF;
    private javax.swing.JTextField txtQualitePF;
    private javax.swing.JTextField txtcategPF;
    // End of variables declaration//GEN-END:variables
}
